<a href="https://colab.research.google.com/github/Tritiksha20/Machine-Learning-College/blob/main/14_CART_LEARNING_ALGORITHM_FOR_CATEGORIZATION.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# ---- Load dataset ----
df = pd.read_csv("/content/iris.csv")
X = df.drop(columns=['target', 'species'])
y = df['target']
feature_names = X.columns.tolist()
class_names = sorted(df['species'].unique())

# ---- Train-test split ----
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=42, stratify=y
)

In [2]:
# =========================================================
# CART using Gini impurity (default in sklearn's DecisionTreeClassifier)
# =========================================================
cart_gini = DecisionTreeClassifier(criterion='gini', max_depth=4, random_state=42)
cart_gini.fit(X_train, y_train)
y_pred_gini = cart_gini.predict(X_test)

print("=" * 60)
print("CART (Gini impurity)")
print("=" * 60)
print(f"Accuracy: {accuracy_score(y_test, y_pred_gini):.4f}")
print("\nClassification Report:")
print(classification_report(y_test, y_pred_gini, target_names=class_names))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_gini))
print("\nFeature importances:")
for name, importance in zip(feature_names, cart_gini.feature_importances_):
    print(f"  {name}: {importance:.4f}")

CART (Gini impurity)
Accuracy: 0.9211

Classification Report:
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        12
  versicolor       0.86      0.92      0.89        13
   virginica       0.92      0.85      0.88        13

    accuracy                           0.92        38
   macro avg       0.92      0.92      0.92        38
weighted avg       0.92      0.92      0.92        38

Confusion Matrix:
[[12  0  0]
 [ 0 12  1]
 [ 0  2 11]]

Feature importances:
  sepal length (cm): 0.0137
  sepal width (cm): 0.0000
  petal length (cm): 0.9387
  petal width (cm): 0.0476


In [3]:
# =========================================================
# CART using entropy criterion (for comparison)
# =========================================================
cart_entropy = DecisionTreeClassifier(criterion='entropy', max_depth=4, random_state=42)
cart_entropy.fit(X_train, y_train)
y_pred_entropy = cart_entropy.predict(X_test)

print("\n" + "=" * 60)
print("CART (Entropy / Information Gain) - for comparison")
print("=" * 60)
print(f"Accuracy: {accuracy_score(y_test, y_pred_entropy):.4f}")

# ---- Predict a new sample ----
new_sample = pd.DataFrame([[5.1, 3.5, 1.4, 0.2]], columns=feature_names)
predicted_class = cart_gini.predict(new_sample)[0]
print(f"\nPrediction for new sample {new_sample.values.tolist()}: {class_names[predicted_class]}")

# ---- Visualize the decision tree ----
plt.figure(figsize=(16, 10))
plot_tree(cart_gini, feature_names=feature_names, class_names=class_names,
          filled=True, rounded=True, fontsize=9)
plt.title("CART Decision Tree (Gini) - Iris Dataset")
plt.tight_layout()
plt.savefig("exp8_decision_tree.png", dpi=150)
print("\nDecision tree plot saved as exp8_decision_tree.png")


CART (Entropy / Information Gain) - for comparison
Accuracy: 0.9211

Prediction for new sample [[5.1, 3.5, 1.4, 0.2]]: setosa

Decision tree plot saved as exp8_decision_tree.png
