<a href="https://colab.research.google.com/github/Tritiksha20/Machine-Learning-College/blob/main/6_Baysien_logistic_regression_and_SVM_for_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC

from sklearn.metrics import (
    accuracy_score, classification_report, confusion_matrix
)

# ---- Load dataset ----
df = pd.read_csv("/content/breast_cancer.csv")
X = df.drop(columns=['target', 'diagnosis'])
y = df['target'] # 0 = malignant, 1 = benign

# ---- Train-test split ----
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=42, stratify=y
)

# ---- Feature scaling ----
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [5]:
bayes_log_reg = LogisticRegression(
    penalty='l2', C=1.0, solver='lbfgs', max_iter=5000
)
bayes_log_reg.fit(X_train_scaled, y_train)
y_pred_blr = bayes_log_reg.predict(X_test_scaled)
y_proba_blr = bayes_log_reg.predict_proba(X_test_scaled)

print("=" * 60)

print("BAYESIAN LOGISTIC REGRESSION (MAP estimate)")
print("=" * 60)
print(f"Accuracy: {accuracy_score(y_test, y_pred_blr):.4f}")
print("\nClassification Report:")
print(classification_report(y_test, y_pred_blr, target_names=['malignant', 'benign']))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_blr))
print("\nSample posterior predictive probabilities (first 5 test points):")
print(np.round(y_proba_blr[:5], 3))

BAYESIAN LOGISTIC REGRESSION (MAP estimate)
Accuracy: 0.9860

Classification Report:
              precision    recall  f1-score   support

   malignant       0.98      0.98      0.98        53
      benign       0.99      0.99      0.99        90

    accuracy                           0.99       143
   macro avg       0.99      0.99      0.99       143
weighted avg       0.99      0.99      0.99       143

Confusion Matrix:
[[52  1]
 [ 1 89]]

Sample posterior predictive probabilities (first 5 test points):
[[0.031 0.969]
 [1.    0.   ]
 [0.441 0.559]
 [0.061 0.939]
 [0.825 0.175]]


In [6]:
svm_clf = SVC(kernel='rbf', C=1.0, gamma='scale', probability=True, random_state=42)
svm_clf.fit(X_train_scaled, y_train)
y_pred_svm = svm_clf.predict(X_test_scaled)

print("\n" + "=" * 60)
print("SUPPORT VECTOR MACHINE (RBF kernel)")
print("=" * 60)
print(f"Accuracy: {accuracy_score(y_test, y_pred_svm):.4f}")
print("\nClassification Report:")
print(classification_report(y_test, y_pred_svm, target_names=['malignant', 'benign']))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_svm))


SUPPORT VECTOR MACHINE (RBF kernel)
Accuracy: 0.9790

Classification Report:
              precision    recall  f1-score   support

   malignant       0.96      0.98      0.97        53
      benign       0.99      0.98      0.98        90

    accuracy                           0.98       143
   macro avg       0.98      0.98      0.98       143
weighted avg       0.98      0.98      0.98       143

Confusion Matrix:
[[52  1]
 [ 2 88]]


In [7]:
print("\n" + "=" * 60)

print("MODEL COMPARISON")
print("=" * 60)
print(f"Bayesian Logistic Regression Accuracy: {accuracy_score(y_test, y_pred_blr):.4f}")
print(f"SVM Accuracy : {accuracy_score(y_test, y_pred_svm):.4f}")


MODEL COMPARISON
Bayesian Logistic Regression Accuracy: 0.9860
SVM Accuracy : 0.9790
